# Generated by Django 5.0.5 on 2024-07-09 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('F5_bigip', '0003_remove_node_created_remove_node_custom_field_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicef5',
            name='clusterf5_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='F5_bigip.clusterf5'),
        ),
    ]
