# Generated by Django 5.0.5 on 2024-07-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('F5_bigip', '0004_alter_devicef5_clusterf5_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='state',
        ),
        migrations.AddField(
            model_name='virtualserver',
            name='source_address',
            field=models.CharField(default='0.0.0.0/0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualserver',
            name='state',
            field=models.CharField(default='Enabled', max_length=200),
        ),
    ]
